### ISSUE TITLE
ads1x15: race condition in unit test

### ISSUE THREAD

**Issue by maruel** [google/periph#334]
https://gist.github.com/gohci-bot/1ba0fd321ddcb295bcd256e2adfe80fb

```
$GOPATH/src/periph.io/x/periph $ go test -race ./...  (exit:1 in 55.551s)
(...)
panic: i2ctest: unexpected Tx() (count #6) expecting i2ctest.IO{Addr:72, W:[]byte{0x1, 0x91, 0x3}, R:[]byte(nil)}

goroutine 6 [running]:
periph.io/x/periph/conn/i2c/i2ctest.errorf(0xc4200c6000, 0x11e48d6, 0x50, 0xc420047d30, 0x4, 0x4, 0x1, 0x2)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/conn/i2c/i2ctest/i2ctest.go:166 +0xe1
periph.io/x/periph/conn/i2c/i2ctest.(*Playback).Tx(0xc4200c6000, 0x1050048, 0xc4200620d0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/conn/i2c/i2ctest/i2ctest.go:127 +0xc79
periph.io/x/periph/conn/i2c.(*Dev).Tx(0xc420062080, 0xc4200620d0, 0x3, 0x3, 0x0, 0x0, 0x0, 0xc420047f48, 0x2)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/conn/i2c/i2c.go:94 +0xb9
periph.io/x/periph/experimental/devices/ads1x15.(*Dev).executePreparedQuery(0xc420062080, 0xc4200620d0, 0x3, 0x3, 0x78bc34, 0x16e360000, 0x0, 0x0, 0x0, 0x0)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/experimental/devices/ads1x15/ads1x15.go:250 +0xda
periph.io/x/periph/experimental/devices/ads1x15.(*analogPin).Read(0xc4200620c0, 0x1, 0x0, 0x0, 0x0)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/experimental/devices/ads1x15/ads1x15.go:412 +0xbf
periph.io/x/periph/experimental/devices/ads1x15.(*analogPin).ReadContinuous.func1(0xc4200c6050, 0xc4200cc000, 0xc4200620c0, 0xc42001e180)
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/experimental/devices/ads1x15/ads1x15.go:438 +0x16b
created by periph.io/x/periph/experimental/devices/ads1x15.(*analogPin).ReadContinuous
	/Users/gohci/gohci/google_periph/src/periph.io/x/periph/experimental/devices/ads1x15/ads1x15.go:430 +0x1af
FAIL	periph.io/x/periph/experimental/devices/ads1x15	0.070s

```

**Comment by maruel** [comment]
Paging @bezineb5.

**Comment by bezineb5** [comment]
Proposed fix: https://github.com/google/periph/pull/336
